---
- name: Install Apache Web Server
  hosts: [server]
  become: yes

  tasks:
    - name: Print OS Family
      debug:
        var: ansible_os_family

    - block: #====== Block for RedHat ======
        - name: Updating repos for CentOS
          yum:
            update_cache: yes

        - name: Install Apache for RedHat
          yum:
            name: httpd
            state: latest

        - name: Start Apache and enable autoboot (RedHat)
          service:
            name: httpd
            state: started
            enabled: yes

        - name: Open port 80 and restart firewall
          shell: firewall-cmd --permanent --add-service=http && firewall-cmd --reload

      when: ansible_os_family=="RedHat"

    - block: #====== Block for Debian======
        - name: Updating repos for Ubuntu
          apt:
            update_cache: yes

        - name: Install Apache for Ubuntu
          apt:
            name: apache2
            state: latest

        - name: Start Apache and enable autoboot (Ubuntu)
          service:
            name: apache2
            state: started
            enabled: yes

        - name: Installing Unzip for Ubuntu
          apt:
            name: unzip
            state: latest

      when: ansible_os_family=="Debian"

    - name: Downloading my website from github.com
      get_url:
        url: https://github.com/01Yura/My_web_site/archive/refs/heads/main.zip
        dest: /var/www/html/
      notify:
        - Extracting My_web_site-main.zip
        - Deleting .github
        - Deleting README.md
        - Moving yura.conf to sites-available
        - Moving yura_ssl.conf to sites-available
        - Deleting My_web_site-main.zip
        - Creating directory yura
        - Deleting all in yura
        - Copying files
        - Executing a2ensite 1
        - Executing a2ensite 2
        - Restart Apache Centos
        - Restart Apache Debian

  handlers:
    - name: Extracting My_web_site-main.zip
      unarchive:
        remote_src: yes
        src: /var/www/html/My_web_site-main.zip
        dest: /var/www/html/

    - name: Deleting .github
      file:
        path: /var/www/html/My_web_site-main/.github
        state: absent

    - name: Deleting README.md
      file:
        path: /var/www/html/My_web_site-main/README.md
        state: absent

    - name: Moving yura.conf to sites-available
      shell: mv /var/www/html/My_web_site-main/yura.conf /etc/apache2/sites-available/

    - name: Moving yura_ssl.conf to sites-available
      shell: mv /var/www/html/My_web_site-main/yura_ssl.conf /etc/apache2/sites-available/

    - name: Deleting my_web_site.conf
      file:
        path: /var/www/html/My_web_site-main/my_web_site.conf
        state: absent

    - name: Deleting My_web_site-main.zip
      file:
        path: /var/www/html/My_web_site-main.zip
        state: absent

    - name: Creating directory yura
      file:
        path: /etc/www/html/yura
        state: directory

    - name: Deleting all in yura
      shell: rm -f /var/www/html/yura/*

    - name: Copying files
      shell: cp -r /var/www/html/My_web_site-main/* /etc/www/html/yura

    - name: Executing a2ensite 1
      shell: a2ensite yura.conf

    - name: Executing a2ensite 2
      shell: a2ensite yura_ssl.conf

    - name: Restart Apache Centos
      service:
        name: httpd
        state: restarted
      when: ansible_os_family=="RedHat"

    - name: Restart Apache Debian
      service:
        name: apache2
        state: restarted
      when: ansible_os_family=="Debian"
