---
- name: Install Apache Web Server
  hosts: [server]
  become: yes

  tasks:
    - name: Print OS Family
      debug:
        var: ansible_os_family

    - block: #====== Block for RedHat ======
        - name: Updating repos for CentOS
          yum:
            update_cache: yes

        - name: Install Apache for RedHat
          yum:
            name: httpd
            state: latest

        - name: Start Apache and enable autoboot (RedHat)
          service:
            name: httpd
            state: started
            enabled: yes

        - name: Open port 80 and restart firewall
          shell: firewall-cmd --permanent --add-service=http && firewall-cmd --reload

      when: ansible_os_family=="RedHat"

    - block: #====== Block for Debian======
        - name: Updating repos for Ubuntu
          apt:
            update_cache: yes

        - name: Install Apache for Ubuntu
          apt:
            name: apache2
            state: latest

        - name: Start Apache and enable autoboot (Ubuntu)
          service:
            name: apache2
            state: started
            enabled: yes

        - name: Installing Unzip for Ubuntu
          apt:
            name: unzip
            state: latest

      when: ansible_os_family=="Debian"

    - name: Downloading my website from github.com
      get_url:
        url: https://github.com/01Yura/{{ folder }}_web_site/archive/refs/heads/main.zip
        dest: /var/www/html/
      notify:
        - Extracting archive
        - Deleting .github
        - Deleting README.md
        - Moving name.conf to sites-available
        - Moving name_ssl.conf to sites-available
        - Deleting archive
        - Creating directory for site
        - Deleting all in site directory
        - Copying files
        - Executing a2ensite 1
        - Executing a2ensite 2
        - Deleting My_web_site-main
        - Restart Apache Centos
        - Restart Apache Debian

  handlers:
    - name: Extracting archive
        remote_src: yes
        src: /var/www/html/{{ folder }}_web_site-main.zip
        dest: /var/www/html/

    - name: Deleting .github
      file:
        path: /var/www/html/{{ folder }}_web_site-main/.github
        state: absent

    - name: Deleting README.md
      file:
        path: /var/www/html/{{ folder }}_web_site-main/README.md
        state: absent

    - name: Moving name.conf to sites-available
      shell: mv /var/www/html/{{ folder }}_web_site-main/{{ folder }}.conf /etc/apache2/sites-available/

    - name: Moving name_ssl.conf to sites-available
      shell: mv /var/www/html/{{ folder }}_web_site-main/{{ folder }}_ssl.conf /etc/apache2/sites-available/

    - name: Deleting archive
      file:
        path: /var/www/html/{{ folder }}_web_site-main.zip
        state: absent

    - name: Creating directory for site
      file:
        path: /etc/www/html/{{ folder }}
        state: directory

    - name: Deleting all in site directory
      shell: rm /var/www/html/{{ folder }}/*
      ignore_errors: yes

    - name: Copying files
      shell: cp /var/www/html/My_web_site-main/* /var/www/html/{{ folder }}/

    - name: Executing a2ensite 1
      shell: a2ensite {{ folder }}.conf

    - name: Executing a2ensite 2
      shell: a2ensite {{ folder }}_ssl.conf

    - name: Deleting My_web_site-main
      file:
        path: /var/www/html/My_web_site-main
        state: absent

    - name: Restart Apache Centos
      service:
        name: httpd
        state: restarted
      when: ansible_os_family=="RedHat"

    - name: Restart Apache Debian
      service:
        name: apache2
        state: restarted
      when: ansible_os_family=="Debian"
