name: deploy_website
on:
  push:
    branches: main
jobs:
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone my repo
        uses: action/checkout@v1

      - name: Deploy
        run: ansible-playbook playbook_install_apache_and_website.yml
